### ISSUE TITLE
Show autolink configuration on plugin page

### ISSUE THREAD

**Issue by MarkMaldaba** [mattermost/mattermost-plugin-autolink#65] opened 2019-07-03 00:07 UTC
Currently, all configuration of the mattermost-autolink plugin must be done directly in config.json. In the long term, this should take place in the interface, but as an interim measure it would be really useful if the plugin page in the system console displayed the current configuration.

This is particularly helpful as a way of cross-checking whether your changes to config.json have taken effect.

**Comment by hanzei** [comment] 2019-07-03 04:51
Thanks for the report @MarkMaldaba. Closing as this is a duplicate of  #31

**Closed** 2019-07-03 04:51 UTC
Labels: Duplicate

**Comment by MarkMaldaba** [comment] 2019-07-03 21:45
Hi there,

This is not a duplicate of #31.  That ticket is to make the plugin configurable via the interface, which would be brilliant.   However, this ticket is to implement an interim measure, to display the current configuration from config.json in a read-only form, until such a time as #31 is implemented.

This ticket becomes invalid once #31 is fixed, but that's not the same thing as saying it's a duplicate.  If that is likely to be done in time for the next release, then I'm happy for this to be closed, but if not I would rather that it were re-opened.

This should be a really simple ticket to resolve, as it just means spitting-out the array as an HTML table.

**Comment by hanzei** [comment] 2019-07-06 21:19
Hey @MarkMaldaba,

You are correct. The two issues aren't the same. But both require similar changes to the Mattermost Plugin system. Hence I suppose that #31 will be implemented first.

I've added your request to #31, so it can be considered as an alternative.

**Comment by MarkMaldaba** [comment] 2019-07-07 17:41
@hanzei - Thanks for the update.  I didn't realise they were both dependent on core changes.

In that context, I'm happy with the way you have resolved this ticket.
