### ISSUE TITLE
Autolink should ignore bot posts. (was: Commit notifications trigger unexpected link preview)

### ISSUE THREAD

**Issue by lieut-data** [mattermost/mattermost-plugin-autolink#94] opened 2020-01-24 12:24 UTC
To avoid clashes with bot-formatted links, Autolink should (optionally?) ignore bot posts.

1/5 recommend adding an "Process posts from Bots", default `false` to the plugin config.

---
Original description:

I recently received a notification in the [message of a commit](https://github.com/mattermost/mattermost-sa-code/commit/528462af4dca50e41011fe1076c76edb00327b5b):

![image](https://user-images.githubusercontent.com/1023171/73068914-ca5d3c80-3e82-11ea-9a13-39edad97c9ab.png)

In my summary, this then resulted in a perhaps unexpected link preview compared to all the other links in the message:

![image](https://user-images.githubusercontent.com/1023171/73068947-df39d000-3e82-11ea-8ccb-25bf3b8fd795.png)

**Comment by levb** [comment] 2020-02-17 22:39
I think the issue should stay here, and be repurposed if the history is important. Autolink will already expose the link config APIs in the next release, no special work needed there AFAIU. We just need to add the code on the GiitHub side to manage the links, and probably a config/feature flag to use this new capability instead of the current in-plugin substitution. cc @jfrerich

**Comment by levb** [comment] 2020-02-17 22:41
(closed by mistake, reopened)

**Comment by lieut-data** [comment] 2020-02-17 22:44
I think there's two separate issues here:
* autolink shouldn't process messages by bots (open for discussion), which I think is the meat of this issue
* GitHub should rely on autolink for link substituion (not as clear to me, and also open for discussion)

One reason to keep this in the GitHub plugin is to solve the second issue, which I guess also solves the first issue? One concern is that this means the GitHub plugin, out of the box, isn't as fully-featured as GitHub + AutoLink, and I have no idea of the lifecycle of these plugin-to-plugin registrations. Seems like a thorny problem and worthy of design + investigation, as compared to solving the original report.

Thoughts on this interpretation?

**Comment by levb** [comment] 2020-02-18 12:13
> autolink shouldn't process messages by bots (open for discussion)

@lieut-data I'd argue against this complexity. Autolink should already ignore substituting _links_ in markdown; Bots should be aware of the markdown nature of the contents and properly encode links in the message bodies if they come from external systems as raw text or other formats. Ditto for the messages that the bots generate.

> GitHub should rely on autolink for link substitution (not as clear to me, and also open for discussion)

2 motives I can think of:
1. Performance - consolidating all substitutions in 1 plugin means 1 MessageWillBePosted RPC/Post, vs 1 for Jira, 1 for GitHub, etc.
2. Predictable order of substitution - something that can be managed in the Autolink plugin if not yet. An example of the problem is, on Community we have the (US) Social Security Number masking autolink "Off" because it ended up affecting the Zoom URLs. To be clear, this problem is not yet solved in a meaningful way; but it appears more solvable within the Autolink plugin than across all of them.

So I'd advocate that we 
a) add "auto-configure-auto-link" option to the GitHub plugin (off by default, mutually exclusive with "legacy"
b) figure out when/how we switch the defaults and migrate

**Comment by lieut-data** [comment] 2020-02-18 14:23
> Autolink should already ignore substituting links in markdown; Bots should be aware of the markdown nature of the contents and properly encode links in the message bodies if they come from external systems as raw text or other formats. Ditto for the messages that the bots generate.

I think this adds more complexity since it requires bots/plugins to artificially encode their payload to avoid some other event they might not have been able to predict. Maybe I want a /real/ link without such a preview, because I'm doing something else, but along comes autolink and decides better for me.

In fact, the simplest model might be to disallow bot rewriting of other bot's posts at the server level: if GitHub wants autolink post-processing, maybe it can opportunistically call out to the autolink API and ask for a payload to be rewritten. Only humans get autolinked.

**Comment by lieut-data** [comment] 2020-02-18 14:25
> a) add "auto-configure-auto-link" option to the GitHub plugin (off by default, mutually exclusive with "legacy"

What happens when the rewrite requires metadata? I think all of these rewrites involve an API call out to GitHub to look up some useful data. I'm having a hard time seeing AutoLink as a general purpose platform to replace the existing `MessageWillBePosted` calls.

**Comment by levb** [comment] 2020-03-03 12:10
> In fact, the simplest model might be... Only humans get autolinked.

It is a 180 from how I was thinking of it, but I am fully persuaded that it is a simple and consistent policy.

**Comment by levb** [comment] 2020-03-03 12:14
> What happens when the rewrite requires metadata?...

@lieut-data hopefully we don't invoke GitHub APIs in MessageWillBePosted - that'd seem inefficient. And if the metadata is cached, I'd argue it should be submitted to Autolink APIs when it changes.

**Comment by levb** [comment] 2020-03-03 12:19
@vespian are you interested in finishing this?

**Comment by vespian** [comment] 2020-03-03 13:01
> @vespian are you interested in finishing this?

Yep.

**Comment by vespian** [comment] 2020-03-07 17:43
Let me know if this is something we are after: https://github.com/mattermost/mattermost-plugin-autolink/pull/98/files

**Comment by lieut-data** [comment] 2020-03-09 16:28
> @lieut-data hopefully we don't invoke GitHub APIs in MessageWillBePosted - that'd seem inefficient. And if the metadata is cached, I'd argue it should be submitted to Autolink APIs when it changes.

@levb, in the GitHub use case we're talking about, it exactly does require a GitHub API call on `MessageWasPosted` (agree that doing this on `MessageWillBePosted` is impractical). I don't think there's anyway we can pre-emptively cache the autolink plugin with knowledge of the contents of an arbitrary GitHub permalink, so this functionality will always live in the GitHub plugin.

**Closed** 2020-03-31 09:51 UTC
Labels: Difficulty/2:Medium, Help Wanted, Tech/Go, Type/Bug
