### ISSUE TITLE
Patterns with < > in the pattern for naming of variables break

### ISSUE THREAD

**Issue by Thoro** [mattermost/mattermost-plugin-autolink#163] opened 2021-05-17 13:11 UTC
I got a pattern with <> : `(?P<ticket>(CREAM|INFRA|CFIT|SET|PMO|PSM)\\-[0-9]+)`

And it's saved as `(?P\u003cticket\u003e(CREAM|INFRA|CFIT|SET|PMO|PSM)\\-[0-9]+)` in the config.json

\autolink list displays it completely mangled as:

`Pattern: (?P[INFRA|CFIT|SET|PMO|PSM)\-[0-9]+)`

Plugin Version: 1.2.2
Mattermost Version: 5.34.0

**Comment by bbodenmiller** [comment] 2022-01-12 02:06
Duplicate of https://github.com/mattermost/mattermost-plugin-autolink/issues/97

**Closed** 2022-01-27 15:03 UTC
Labels: Duplicate
