### ISSUE TITLE
Apply transformations on render, not on save

### ISSUE THREAD

**Issue by MarkMaldaba** [mattermost/mattermost-plugin-autolink#66] opened 2019-07-03 00:11 UTC
> This plugin creates regular expression (regexp) patterns that are
> reformatted into a Markdown link before the message is saved into
> the database.

There are real issues with this happening before being saved, rather than happening before rendering, as it means it is a lossy conversion that cannot be updated to fix e.g. bad configuration or URL changes.

It also means that anyone editing a post will not see what they typed, but some modified version, breaking the principal of least surprise and potentially causing confusion and errors.

The plugin should be modified so that the transformation takes place when the post is rendered, rather than when it is saved.  If the current behaviour is useful to some people then this could be an additional setting in the config array (e.g. ````"pre-save": true````).

Mattermost may need an extra hook to allow a pre-render transformation.

**Comment by hanzei** [comment] 2019-07-03 04:54
Duplicate of https://github.com/mattermost/mattermost-plugin-autolink/issues/34

**Closed by hanzei** 2019-07-03 04:54 UTC

**Comment by MarkMaldaba** [comment] 2019-07-03 21:46
Apologies for the duplicate - I even searched before posting, but must have used different terms as it wasn't found.
